In [1]:
import numpy as np

In [4]:
A = np.random.randint(-10, 10, 18).reshape((3, 6))

In [5]:
A

array([[-9,  2, -3, -7, -5, -2],
       [-1, -5,  5,  3,  5, -1],
       [-7, -5, -7, -2,  1,  3]])

In [6]:
A_transpose = A.T

In [8]:
A_transpose

array([[-9, -1, -7],
       [ 2, -5, -5],
       [-3,  5, -7],
       [-7,  3, -2],
       [-5,  5,  1],
       [-2, -1,  3]])

In [11]:
A.dot(A_transpose)

array([[172, -60,  77],
       [-60,  86,  -7],
       [ 77,  -7, 137]])

In [12]:
A_transpose.dot(A)

array([[131,  22,  71,  74,  33,  -2],
       [ 22,  54,   4, -19, -40, -14],
       [ 71,   4,  83,  50,  33, -20],
       [ 74, -19,  50,  62,  48,   5],
       [ 33, -40,  33,  48,  51,   8],
       [ -2, -14, -20,   5,   8,  14]])

Generally, $A^T \times A \ne A \times A^T$, the only exception in the $\Re$ field is when $A$ is a symetric matrix. For a symetric matrix, $A^T = A$, and in this case, $A$ must be a square matrix.

An example of a symetric matrix is:
\begin{equation}
    A = \left(
        \begin{matrix}
            2&3&5\\
            3&5&6\\
            5&6&1\\
        \end{matrix}
    \right)
\end{equation}

In [13]:
B = np.array(
    [[2, 3, 5],
    [3, 4, 6],
    [5, 6, 1]]
)

B_transpose = B.T

In [14]:
B.dot(B_transpose)

array([[38, 48, 33],
       [48, 61, 45],
       [33, 45, 62]])

In [15]:
B_transpose.dot(B)

array([[38, 48, 33],
       [48, 61, 45],
       [33, 45, 62]])